<a href="https://colab.research.google.com/github/yosti829-spec/data_science-day-3/blob/main/data_science_task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1: Create Your Own Dataset (Foundation)**

**Task: Build a DataFrame from a Dictionary**

 @ Use a dictionary to create a dataset of your choice.

@ It needs to have 5 Columns (features)

@ It needs to have 15 rows

@ It needs to assign custom index.

In [11]:
import pandas as pd

data = {
    "Name": ["Chala Ashenafi", "Fedawak Hailu ", "Sara Bekele", "Marta Alem",
             "Dawit Kebede", "Hana Tesfaye", "Samuel Girma", "Ruth Daniel",
             "Bereket Yohannes", "Liya Mekonnen", "Nahom Desta", "Selam Worku",
             "Yonatan Fikre", "Rahel Tadesse", "Fitsum Haile"],

    "Sex": ["M","M","F","F","M","F","M","F","M","F","M","F","M","F","M"],

    "Department": ["CSE","SE","ECE","civil eng.","water eng.","mechanical eng.",
                   "CSE","SE","ECE","civil eng.","ECE","SE","CSE","SE","ECE"],

    "CGPA": [3.5,3.2,3.8,3.6,1.2,3.7,3.1,3.9,2.8,3.4,3.0,3.6,2.7,3.8,3.3],

    "Age": [21,22,20,23,24,21,22,20,25,23,24,22,26,21,23]
}

# Custom index
ids = [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115]

df = pd.DataFrame(data, index=ids)

# Set index name (NO SPACE before this line)
df.index.name = "Student_ID"

# Pass/Fail
df["pass/fail"] = df["CGPA"].apply(lambda x: "Fail" if x < 1.5 else "Pass")

print(df)

                        Name Sex       Department  CGPA  Age pass/fail
Student_ID
101           Chala Ashenafi   M              CSE   3.5   21      Pass
102           Fedawak Hailu    M               SE   3.2   22      Pass
103              Sara Bekele   F              ECE   3.8   20      Pass
104               Marta Alem   F       civil eng.   3.6   23      Pass
105             Dawit Kebede   M       water eng.   1.2   24      Fail
106             Hana Tesfaye   F  mechanical eng.   3.7   21      Pass
107             Samuel Girma   M              CSE   3.1   22      Pass
108              Ruth Daniel   F               SE   3.9   20      Pass
109         Bereket Yohannes   M              ECE   2.8   25      Pass
110            Liya Mekonnen   F       civil eng.   3.4   23      Pass
111              Nahom Desta   M              ECE   3.0   24      Pass
112              Selam Worku   F               SE   3.6   22      Pass
113            Yonatan Fikre   M              CSE   2.7   26      Pass
114            Rahel Tadesse   F               SE   3.8   21      Pass
115             Fitsum Haile   M              ECE   3.3   23      Pass

# **Part 2: Real Dataset — Titanic**

In [20]:
from google.colab import files
uploaded = files.upload()

In [27]:
import pandas as pd

df = pd.read_csv('dataset-2.csv')

# **Step 1: Exploration**

This command is used to display the first 5 rows of the dataset.
It helps to understand the structure and columns.

In [32]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

This command provides a summary of the dataset including the number of rows, column names, data types, and missing values. It is useful for identifying data cleaning needs.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

This command shows statistical information about numerical columns such as mean, minimum, maximum, and standard deviation. It helps to understand the distribution of the data.

In [30]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# **Step 2: Data Cleaning**

Handling Missing Values in Age Column
The missing values in the Age column are replaced with the median value. Median is used because it is not affected by extreme values.

In [34]:
df['Age'] = df['Age'].fillna(df['Age'].median())

Handling Missing Values in Embarked Column
The missing values in the Embarked column are filled with the mode (most frequent value).

In [35]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

Dropping Cabin Column
The Cabin column is removed because it contains many missing values and is not useful for analysis.

In [36]:
df = df.drop(columns=['Cabin'])

Removing Duplicate Rows
Duplicate rows are removed to ensure data accuracy and avoid repeated information.

In [43]:
df = df.drop_duplicates()

Checking the Dataset After Cleaning
This step ensures that missing values are handled and the dataset is clean.

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

# **Step 3: Data Analysis**

Survival Rate by Gender
This analysis shows the survival rate of passengers based on gender. It helps to understand whether males or females had a higher chance of survival.

In [42]:
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Survival Rate by Passenger Class
This shows how survival rate varies across different passenger classes (1st, 2nd, 3rd). It helps to understand the impact of social class on survival.

In [41]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Average Age per Class
This calculates the average age of passengers in each class. It helps to analyze the age distribution among classes.

In [40]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

Survival Rate by Age Group
Passengers are divided into age groups (Child, Teen, Adult, Senior). This helps to see which age group had higher survival rates.

In [39]:
df['AgeGroup'] = pd.cut(df['Age'],
                       bins=[0, 12, 18, 60, 100],
                       labels=['Child', 'Teen', 'Adult', 'Senior'])

df.groupby('AgeGroup')['Survived'].mean()

/tmp/ipykernel_9250/1572227424.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('AgeGroup')['Survived'].mean()

AgeGroup
Child     0.579710
Teen      0.428571
Adult     0.365753
Senior    0.227273
Name: Survived, dtype: float64

# **Step 4: Filtering**

Female Passengers Who Survived
This filters the dataset to show only female passengers who survived the Titanic disaster.

In [44]:
df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C,Adult
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C,Teen
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult

Children Who Survived
This filters passengers who are considered children (Age less than 12) and survived.

In [45]:
df[(df['Age'] < 12) & (df['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,S,Child
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,C,Child
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,S,Child
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S,Child
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,S,Child
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,S,Child
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,S,Child
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,S,Child
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,S,Child
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,S,Child
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,S,Child
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,S,Child
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,Child
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,S,Child
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,S,Child
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,C,Child
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,S,Child
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,S,Child
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,C,Child
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,C,Child
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,S,Child
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,S,Child
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,S,Child
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,S,Child
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,S,Child
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,S,Child
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,C,Child
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,C,Child
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,S,Child
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,S,Child
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,S,Child
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,S,Child
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,S,Child
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,S,Child
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,S,Child
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,C,Child
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,C,Child
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,Child
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,Child

1st Class Passengers Who Survived
This filters passengers from 1st class who survived, showing those with a higher survival probability.

In [47]:
df[(df['Pclass'] == 1) & (df['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Adult
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S,Adult
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S,Adult
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Adult

**STE P 5: INSIGHTS**
## **1. Who was more likely to survive?**

Female passengers were more likely to survive than male passengers.
The survival rate for females is higher because historically, women and children were prioritized during the evacuation.

**2. Did class affect survival?**

Yes, the passenger class had a strong impact on survival:


1st Class → highest survival rate

2nd Class → medium survival rate

3rd Class → lowest survival rate

This shows that wealth and social status influenced who survived.

**3. Were children prioritized?**

Yes. Children (under 12 years old) had a higher survival rate compared to adults.
This indicates that children were given priority during rescue.

4. **Which combination had the highest survival rate?**

The combination of female + 1st class + child had the highest
probability of survival.

This shows that being female, in a higher class, and young increased chances of surviving the disaster.